import { storage } from 'uxp';
import { getChannelHistograms } from './histogram';

function formatHistogram(histogram: number[]): string {
	return `[${histogram.join(', ')}]`;
}

/** Prompts the user for a save location, then writes the active document's red/green/blue channel histograms to a generated TypeScript file. */
export async function writeChannelHistogramsFile(): Promise<void> {
	const histograms = await getChannelHistograms();

	const file = await storage.localFileSystem.getFileForSaving('histograms.ts', { types: ['ts'] });
	if (!file) {
		console.log('[c41] writeChannelHistogramsFile: save cancelled');
		return;
	}

	const contents = `// Generated by C41 tools: channel histograms (256-entry pixel counts) of the active document.

export const redHistogram: number[] = ${formatHistogram(histograms.get('Red')!)};

export const greenHistogram: number[] = ${formatHistogram(histograms.get('Green')!)};

export const blueHistogram: number[] = ${formatHistogram(histograms.get('Blue')!)};
`;

	await file.write(contents);
}
